#!/usr/bin/python

import sys, subprocess, datetime

# bz2 -> -j
#tar cvzf $1.tar.gz $1

cmd = "tar"
arg = "czf"	# Add v for verbose mode; j for bz2 instead of z
inp = ""
out = ""

if len(sys.argv) < 2:
	print "Usage: pack <file or directory> [-o <output name>] [-d]"
	sys.exit(0)

inp = None
out = None
date = ""

# Parse args
i = 1
while i < len(sys.argv):
	curr = sys.argv[i]
	if curr.startswith("-"):
		i += 1
		if curr[1] == "o":
			out = sys.argv[i]
		elif curr[1] == "d":
			date = datetime.datetime.now().strftime("_%Y-%m-%d_%H.%M")
		else:
			raise Exception("Unknown option")
	else:
		inp = curr
	i += 1

if inp.endswith("/"):
	inp = inp[:len(inp)-1]

if out is None:
	out = inp

out = out + date + ".tar.gz"

callstr = cmd + " " + arg + " " + out + " " + inp
print callstr

subprocess.call(callstr, shell=True)

